export default {
  TIMEOUT_ERROR_CODES: ['ECONNABORTED'],
  NODEJS_CONNECTION_ERROR_CODES: ['ENOTFOUND', 'ECONNREFUSED', 'ECONNRESET'],
  STATUS_ERROR_CODES: ['ERR_BAD_REQUEST', 'ERR_BAD_RESPONSE'],
};
